### ISSUE TITLE
[Feature request] Play bron cena themes overlapping option

### ISSUE THREAD

**Issue by tryallthethings** [SadRobotGG/BronCena#6]
Hey guys!

I really love the addon. It puts a smile on my face every time the bron cena theme starts. Just saw your latest version patchnotes:
`FIXED: Sounds shouldn't overlap, so if a bunch of Brons appear rapidly, it will just restart the theme and not playing a bunch all out of sync`
Could you please make it an option to switch between this fix and the original version? I found it absolutely hilarious having the bron cena theme playing 3 or 4 times in parallel.

Thanks
Stefan

**Comment by DavidMoore** [comment]
Hi! Sorry I completely missed this request. I can absolutely add this back in as an option.

**Comment by tryallthethings** [comment]
Thank you. And I love the patchnotes for this!  🤣

**Comment by DavidMoore** [comment]
Nice! Is it working fine for you? Was tricky for me to test properly.

**Comment by tryallthethings** [comment]
Yes, works great. The sweet sound of multiple Bron cena sounds reach my ears once more 😄

**Comment by DavidMoore** [comment]
Excellent! Enjoy :D
