### ISSUE TITLE
Benny hill

### ISSUE THREAD

**Issue by YakirTwil** [SadRobotGG/BronCena#7]
It would be funny if you add the benny hill theme song when ever you get the wo relic buff that gives you invis and make you run fast
BTW just wanted to say Bron Cena is awesome makes every Bron feel 100 times better

**Comment by DavidMoore** [comment]
This is a good idea! I'll try dedicate some time to this this weekend.

**Comment by DavidMoore** [comment]
I have this working, I'll do more testing and release it soon!

**Comment by tryallthethings** [comment]
I love this idea. But it didn't work once for me in the last 2 released versions, while the darkness thing works just fine. Do I need to do anything besides enabling it?

**Comment by tryallthethings** [comment]
Nevermind that. Fixed it for you 😆 -> https://github.com/SadRobotGG/BronCena/pull/10
